### ISSUE TITLE
Explain how sender know whether the recipient can obtain a key using kid

### ISSUE THREAD

**Issue by erdtman** [cwt-cnf/i-d#11]
review comment form Roman

(8) Page 7, Section 3.4, Per "The proof-of-possession key can also be identified by the use of a Key ID instead of communicating the actual key, provided the recipient is able to obtain the identified key using the Key ID."  How would the sender know whether the recipient can "obtain the key using the Key ID"?  Additionally, I would recommend adding language that states that this retrieval process is out of scope for this draft.

The sender needs to know from the application context what cnf method to use. I think we should add both this and a comment saying that retrieval process is out of scope

**Comment by hannestschofenig** [comment]
In https://github.com/cwt-cnf/i-d/pull/27 I cleaned up this text. I don't know why we need to write about how the KIDs are created. If someone decides to use KID to send keys "per reference" (instead of "per value") then they also have to find out how to create them so that there are no collisions. There is no magic here.
